# DigitalOcean App Platform spec for SnoopTrade backend API.
# Replace github.repo with your repo (e.g. owner/SnoopTrade) and set env values in the DO dashboard.
name: snooptrade-api

services:
  - name: api
    github:
      repo: nevilpadariya/SnoopTrade
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: MONGODB_URI
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: ""
      - key: MONGO_URI
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: ""
      - key: GOOGLE_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: ""
      - key: ADMIN_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: ""
